export const MOCK_SACCOS = [
  {
    id: 1,
    name: "Elimu Sacco",
    code: "ELIM001",
    county: "Nairobi",
    members: 4820,
    status: "active",
    tier: "Premium",
    regNo: "SASRA/R/2022/014",
    description: "Primarily serves the education sector workforce, providing competitive savings dividend rates and structural asset development financing options.",
    address: "7th Floor, Elimu Center, Upperhill, Nairobi",
    phone: "+254 20 2711122",
    email: "info@elimusacco.co.ke",
    website: "https://www.elimusacco.co.ke"
  },
  {
    id: 2,
    name: "Afya Bora Sacco",
    code: "AFYA002",
    county: "Mombasa",
    members: 2310,
    status: "active",
    tier: "Standard",
    regNo: "SASRA/R/2023/089",
    description: "Dedicated to healthcare workers and medical practitioners across the coastal region with instant emergency medical loan product facilities.",
    address: "Afya Plaza, Near Coast General Hospital, Mombasa",
    phone: "+254 41 2244556",
    email: "support@afyaborasacco.co.ke",
    website: "https://www.afyaborasacco.co.ke"
  },
  {
    id: 3,
    name: "Wakulima Sacco",
    code: "WAKU003",
    county: "Nakuru",
    members: 6750,
    status: "pending",
    tier: "Enterprise",
    regNo: "SASRA/R/2025/112",
    description: "A large agricultural cooperative supporting smallholder crop and livestock farmers with seasonal loan repayment structures paired to harvest cycles.",
    address: "Wakulima House, George Morara Avenue, Nakuru",
    phone: "+254 51 2210088",
    email: "nakuru@wakulimasacco.co.ke",
    website: "https://www.wakulimasacco.co.ke"
  },
  {
    id: 4,
    name: "Imara Sacco",
    code: "IMARR04",
    county: "Kisumu",
    members: 1540,
    status: "inactive",
    tier: "Standard",
    regNo: "SASRA/R/2021/045",
    description: "Formed by MSME traders within the Lake Victoria basin region, currently undergoing core ledger infrastructure restructuring.",
    address: "Imara Building, Oginga Odinga Street, Kisumu",
    phone: "+254 57 2024411",
    email: "operations@imarasacco.co.ke",
    website: "https://www.imarasacco.co.ke"
  },
  {
    id: 5,
    name: "Nguvu Sacco",
    code: "NGVU005",
    county: "Eldoret",
    members: 3200,
    status: "active",
    tier: "Premium",
    regNo: "SASRA/R/2023/034",
    description: "Serves public transport networks, logistics operators, and local manufacturing employees across Uasin Gishu county.",
    address: "Nguvu Towers, Uganda Road, Eldoret",
    phone: "+254 53 2061177",
    email: "info@nguvusacco.co.ke",
    website: "https://www.nguvusacco.co.ke"
  },
  {
    id: 6,
    name: "Hazina Sacco",
    code: "HAZI006",
    county: "Nyeri",
    members: 8940,
    status: "active",
    tier: "Enterprise",
    regNo: "SASRA/R/2020/003",
    description: "A prominent county-wide fund catering to public service employees, civil servants, and regional self-help investment clusters.",
    address: "Hazina Building, Gakere Road, Nyeri",
    phone: "+254 61 2034455",
    email: "nyeri@hazinasacco.co.ke",
    website: "https://www.hazinasacco.co.ke"
  },
  {
    id: 7,
    name: "Mwalimu National Sacco",
    code: "MWAL007",
    county: "Machakos",
    members: 12450,
    status: "active",
    tier: "Enterprise",
    regNo: "SASRA/R/2019/001",
    description: "An enterprise institutional tier hub supporting primary, secondary, and tertiary institution teaching networks with digital banking wrappers.",
    address: "Mwalimu Complex, Mwatu Wa Ngoma Road, Machakos",
    phone: "+254 44 2120033",
    email: "machakos@mwalimunational.co.ke",
    website: "https://www.mwalimunational.co.ke"
  },
  {
    id: 8,
    name: "Chama Stars Sacco",
    code: "CHAM008",
    county: "Thika",
    members: 980,
    status: "pending",
    tier: "Standard",
    regNo: "SASRA/R/2026/019",
    description: "A boutique micro-savings cooperative focused entirely on social investment group groups and micro-business credit lines.",
    address: "Stars Arcade, Commercial Street, Thika",
    phone: "+254 67 31255",
    email: "hello@chamastarssacco.co.ke",
    website: "https://www.chamastarssacco.co.ke"
  },
  {
    id: 9,
    name: "Asali Nyuki Sacco",
    code: "ASAL009",
    county: "Garissa",
    members: 1150,
    status: "inactive",
    tier: "Standard",
    regNo: "SASRA/R/2022/076",
    description: "Caters specifically to honey producers and ASAL livestock pastoralist supply chains across Garissa and surrounding hinterlands.",
    address: "Beehive House, Kismayu Road, Garissa",
    phone: "+254 46 2103344",
    email: "admin@asalinyukisacco.co.ke",
    website: "https://www.asalinyukisacco.co.ke"
  },
  {
    id: 10,
    name: "Sukari West Sacco",
    code: "SUKA010",
    county: "Kakamega",
    members: 4120,
    status: "active",
    tier: "Premium",
    regNo: "SASRA/R/2024/052",
    description: "Serves outgrower sugar outgrowers, refinery workers, and retail delivery transport networks in Western Kenya.",
    address: "Sukari Plaza, Mumias-Kakamega Road, Kakamega",
    phone: "+254 56 3102211",
    email: "connect@sukariwestsacco.co.ke",
    website: "https://www.sukariwestsacco.co.ke"
  },
  {
    id: 11,
    name: "Meru Farmers Sacco",
    code: "MERU011",
    county: "Meru",
    members: 7310,
    status: "active",
    tier: "Premium",
    regNo: "SASRA/R/2021/011",
    description: "Specialized financial pooling infrastructure optimized for coffee, tea, and dairy farming production communities in Mount Kenya East.",
    address: "Farmers Union Plaza, Tom Mboya Street, Meru",
    phone: "+254 64 3130099",
    email: "operations@merufarmerssacco.co.ke",
    website: "https://www.merufarmerssacco.co.ke"
  },
  {
    id: 12,
    name: "Gusii Pioneers Sacco",
    code: "GUSI012",
    county: "Kisii",
    members: 2890,
    status: "pending",
    tier: "Standard",
    regNo: "SASRA/R/2025/204",
    description: "A newly incorporated community-led cooperative supporting real estate builders and youth enterprise clusters across Kisii county.",
    address: "Pioneers House, Hospital Road, Kisii",
    phone: "+254 58 2030011",
    email: "support@gusiipioneers.co.ke",
    website: "https://www.gusiipioneers.co.ke"
  }
];